Dhanraj/D_app/urls.py
from django.contrib import admin
from django.urls import path
from  . import views
app_name='D_app'
urlpatterns = [
    path('',views.home,name='home'),
    path('buy/',views.buy,name='buy'),    
    path('sell/',views.sell,name='sell'),
    path('donate/',views.donate,name='donate'),
    path('index/',views.index,name='index'),
    path('sign_up/',views.sign_up,name='sign_up'),
    path('log_in/',views.log_in,name='log_in'),
    path('log_out/',views.log_out,name='log_out'),
    
    
]

Dhanraj/Dhanraj/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('',include('D_app.urls'),name='app'),
    path('admin/', admin.site.urls),
]

Dhanraj/D_app/models.py
from django.db import models

# Create your models here.

Dhanraj/D_app/views.py
from django.urls import reverse
from django.db import IntegrityError
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login,logout

# Create your views here.
def buy(request):
    return render(request,'D_app/buy.html')

def sell(request):
    return render(request,'D_app/sell.html')

def donate(request):
    return render(request,'D_app/donate.html')
def index(request):
    return render(request,'D_app/index.html')


def home(request):
    return render(request,'D_app/home.html')

def sign_up(request):
    msg=''
    if request.method == 'POST':
        username = request.POST['username']
        fname = request.POST['fname']
        lname = request.POST['lname']
        email = request.POST['email']
        pass1 = request.POST['psw1']
        pass2 = request.POST['psw2']
        if pass1 == pass2:
            try:
                u = User.objects.create_user(username=username,first_name=fname,last_name=lname,email=email,password=pass1)
                u.save()
                alert='User Created Successfully !!..'
            except IntegrityError :
                msg='username alerady exist'
                return render(request,'D_app/sign_up.html',{'msg':msg})
            return redirect(reverse('D_app:log_in'))
        else:
            msg='Password does not match'
    return render(request,'D_app/sign_up.html',{'msg':msg})


def log_in(request):
    msg=''
    if request.method == 'POST':
        username = request.POST['uname']
        pass1= request.POST['psw']
        u = authenticate(username= username,password=pass1)
        if u is not None:
            login(request,user=u)
            return redirect(reverse('D_app:index'))
        else:
            msg='Invalid Details'
    return render(request,'D_app/log_in.html',{'msg':msg})

def log_out(request):
    logout(request)
    return redirect(reverse('D_app:home'))

Dhanraj/D_app/templates/D_app/buy.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'buy.css' %}">
    <title>Buy plants</title>
</head>
<h2>Buy Items</h2>
<body>
    <tr>
        <td>
        <figure>
            <img src="{% static '1.jpg' %}" alt="image"><br>
            <figcaption>200Rs.<button>BUY</button></figcaption>
        </figure>
    </td>
    <td>
        <figure>
            <img src="{% static '2.jpg' %}" alt="image"><br>
            <figcaption>150Rs.<button>BUY</button></figcaption>
        </figure>
    </td>
    <td>
        <figure>
            <img src="{% static '3.jpg' %}" alt="image"> <br>
            <figcaption>300Rs.<button>BUY</button></figcaption>
        </figure>
    </td>
</tr>
<tr>
    <td>
    <figure>
        <img src="{% static '4.jpg' %}" alt="image"><br>
        <figcaption>200Rs.<button>BUY</button></figcaption>
    </figure>
</td>
<td>
    <figure>
        <img src="{% static '5.jpg' %}" alt="image"><br>
        <figcaption>150RS.<button>BUY</button></figcaption>
    </figure>
</td>
<td>
    <figure>
        <img src="{% static '6.jpg' %}" alt="image"> <br>
        <figcaption>150Rs.<button>BUY</button></figcaption>
    </figure>
</td>
    </tr>
</table>
</body>
</html>

Dhanraj/D_app/templates/D_app/donate.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'donate.css' %}">
    <title>Document</title>
</head>
<body>
  <h2>Leaf now!</h2>
    <div>
        <form>
          <button id="rzp-button1">
            <i class="fas fa-donate"></i>&nbsp;&nbsp;Donate here
          </button>
          <script src="https://checkout.razorpay.com/v1/checkout.js"></script>
          <script>
            var options = {
              key: "rzp_test_aIfnpuWEudWnID", // Enter the Key ID generated from the Dashboard
              amount: "5000", // Amount is in currency subunits. Default currency is INR. Hence, 50000 refers to 50000 paise
              currency: "INR",
              name: "Dhanraj Bongale",
              description: "Please lend a Helping hand",
              handler: function (response) {
                if (
                  typeof response.razorpay_payment_id == "undefined" ||
                  response.razorpay_payment_id < 1
                ) {
                  swal({
                    title: "Please try again later!",
                    icon: "error",
                    button: "Close",
                  });
                } else {
                  swal({
                    title: "Thank You!",
                    icon: "success",
                    button: "Close",
                  });
                }
              },
              theme: {
                color: "#3399cc",
              },
            };
            var rzp1 = new Razorpay(options);
            document.getElementById("rzp-button1").onclick = function (
              e
            ) {
              rzp1.open();
              e.preventDefault();
            };
          </script>
        </form>
      </div>
</body>
</html>

Dhanraj/D_app/templates/D_app/home.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'home.css' %}">
    <title>Leaf Now</title>
</head>
<body>
    <nav>
    <ul>
        <li><a href="{% url 'D_app:log_in' %}">Login</a></li>
        <li><a href="{% url 'D_app:sign_up' %}">Signup</a></li>
    </ul>
</nav>
<img src="{% static 'lead.jpg' %}" alt="Leaf Now">
</body>
</html>

Dhanraj/D_app/templates/D_app/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'index.css' %}">
    <title>Leaf Now</title>
</head>
<body>
    <h2>Leaf Now</h2>

    <div class="cnt">
<nav>
    <ul>
        <li><a href="{% url 'D_app:buy' %}">BUY</a></li>
        <li><a href="{% url 'D_app:sell' %}">SELL</a></li>
        <li><a href="{% url 'D_app:donate' %}">DONATE</a></li>
        <li><a href="{% url 'D_app:log_out' %}">LOGOUT</a></li>
    </ul>
    
</nav>
</div><br><br>  
<img src="{% static 'leaf.jpg' %}" alt="">
</body>
</html>

Dhanraj/D_app/templates/D_app/log_in.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'login.css' %}">
    <title>Leaf Now</title>
</head>
<body>
<div class="cnt">
    <h2>Login Form</h2>
    
    <form action="{% url 'D_app:log_in' %}" method="POST">
      {% csrf_token %}
      <div class="imgcontainer">
        <img src="{% static 'leaf.jpg' %}" alt="Avatar" class="avatar">
      </div>
    
      <div class="container">
        <label for="uname"><b>Username</b></label>
        <input type="text" placeholder="Enter Username" name="uname" value="{{request.user.username}}"required>
    
        <label for="psw"><b>Password</b></label>
        <input type="password" placeholder="Enter Password" name="psw" required>
            
        <button type="submit">Login</button>
        <label>
          {% if msg %}
          <p style='color : red'>*{{msg}}</p>
          {% endif %}
          <input type="checkbox" checked="checked" name="remember"> Remember me
        </label>
      </div>
    
      <div class="container" style="background-color:#f1f1f1">
      </div>
    </form>
</div>
    </body>
    </html>
    

Dhanraj/D_app/templates/D_app/sell.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'sell.css' %}">
    <title>Sell plants</title>
</head>
<body>
    <h2>Sell plants here...</h2>
    <img src="{% static 'll.jpg' %}" alt="">
    <div class="cnt">
    

    <label for="f">Upload the plants photos:</label><br>
    <input type="file"><br><br>
    <label for="de">Description</label><br>
    <textarea name="comment" form="usrform">Enter text here...</textarea>
</div>
</body>
</html>

Dhanraj/D_app/templates/D_app/sign_up.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'sign_up.css' %}">
    <title>Leaf Now</title>
</head>
<body>

  <div class="cnt">
    <form action="{% url 'D_app:sign_up' %}"   method="POST"  style="border:1px solid #ccc">
        {% csrf_token %}
        <div class="container">
          <h2>Sign Up</h2>
          <p>Please fill in this form to create an account.</p>
          <hr>
          <label for="username"><b>Username</b></label>
          <input type="text" placeholder="Enter Username" name="username" required>
          
          <label for="fname"><b>First Name</b></label>
          <input type="text" placeholder="Enter First Name" name="fname" required>
          
          <label for="lname"><b>Last Name</b></label>
          <input type="text" placeholder="Enter Last Name" name="lname" required>


          <label for="email"><b>Email</b></label>
          <input type="text" placeholder="Enter Email" name="email" required>
      
          <label for="psw1"><b>Password</b></label>
          <input type="password" placeholder="Enter Password" name="psw1" required>
      
          <label for="psw2"><b>Repeat Password</b></label>
          <input type="password" placeholder="Repeat Password" name="psw2" required>
      
          {% if msg %}
          <p style='color : red'>*{{msg}}</p>
          {% else %}
          <label>
            <input type="checkbox" checked="checked" name="remember" style="margin-bottom:15px"> Remember me
          </label>

   
      
          <p>By creating an account you agree to our <a href="#" style="color:dodgerblue">Terms & Privacy</a>.</p>
          {% endif %}
          <div class="clearfix">
            <button type="button" class="cancelbtn">Cancel</button>
            <button type="submit" class="signupbtn">Sign Up</button>
          </div>
        </div>
      </form>
    </div>
</body>
</html>